//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalvameMasterRestApi.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendamiento
    {
        public long Id { get; set; }
        public long IdTrabajador { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime FchVisita { get; set; }
        public System.DateTime FchAgendamiento { get; set; }
        public string Direccion { get; set; }
        public short IdRegion { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Telefono { get; set; }
        public string Observacion { get; set; }
        public Nullable<short> IdEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Region Region { get; set; }
        public virtual Trabajador Trabajador { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
