//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalvameMasterRestApi.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackTrabajador
    {
        public long Id { get; set; }
        public long IdTrabajador { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime FchFeedback { get; set; }
        public decimal Valoracion { get; set; }
        public string Observacion { get; set; }
    
        public virtual Trabajador Trabajador { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
