//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalvameMasterRestApi.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public long Id { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime FchInscripcion { get; set; }
        public string Token { get; set; }
        public System.DateTime FchExpiracion { get; set; }
        public short IdEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
