//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalvameMasterRestApi.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajeSalida
    {
        public long Id { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string Html { get; set; }
        public string Asunto { get; set; }
        public System.DateTime FchInsert { get; set; }
        public short NroIntentos { get; set; }
        public Nullable<System.DateTime> FchUpdate { get; set; }
        public short IdEstado { get; set; }
    }
}
