//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalvameMasterRestApi.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajador()
        {
            this.Agendamiento = new HashSet<Agendamiento>();
            this.FeedbackTrabajador = new HashSet<FeedbackTrabajador>();
        }
    
        public long Id { get; set; }
        public long IdPersona { get; set; }
        public short IdTipoTrabajador { get; set; }
        public System.DateTime FchInicioTrabajador { get; set; }
        public decimal PrecioHora { get; set; }
        public decimal PrecioVisita { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public short IdRegion { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamiento> Agendamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackTrabajador> FeedbackTrabajador { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Region Region { get; set; }
        public virtual TipoTrabajador TipoTrabajador { get; set; }
    }
}
