//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalvameMasterRestApi.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario1
    {
        public long Id { get; set; }
        public long IdPersona { get; set; }
        public string Password { get; set; }
        public System.DateTime FchCreate { get; set; }
        public short IdEstado { get; set; }
    }
}
